/**
 * Automated Reorder Scheduler
 * Mirrors Odoo 19 Inventory › Replenishment — reorder rules scheduler.
 *
 * For every active product that has reorderingRules configured:
 *   - If the product's on-hand stock (summed from ProductStock) falls below any rule's minQty,
 *     and that rule has no open RFQ already in flight,
 *     the scheduler creates a draft RFQ via PurchaseOrderService.
 *
 * Designed to be called from a cron job or an admin mutation (manual trigger).
 * Can be wired to a setInterval in the server startup (apps/api/src/index.ts) for automatic execution.
 *
 * Usage (manual trigger via GraphQL):
 *   mutation { runReorderScheduler(organizationId: "...") { triggered products { productId productName qty vendorId } } }
 */

import { Product } from '../modules/product/model'
import { ProductStockService } from '../modules/product-stock/service'
import { PurchaseOrderService } from '../modules/purchase-order/service'
import { logger } from './logger'

const productStockService = new ProductStockService()
const poService = new PurchaseOrderService()

interface ReorderResult {
  productId: string
  productName: string
  ruleId: string
  warehouseId: string | null
  onHandQty: number
  minQty: number
  maxQty: number
  qtyToOrder: number
  vendorId: string
  unitPrice: number
  poCreated: boolean
  poId?: string
  error?: string
}

interface SchedulerOutput {
  triggered: boolean
  scanned: number
  replenished: number
  products: ReorderResult[]
}

export async function runReorderScheduler(organizationId: string, userId = 'scheduler'): Promise<SchedulerOutput> {
  const results: ReorderResult[] = []
  let scanned = 0
  let replenished = 0

  // Load all active purchasable products for this org that have reordering rules
  const products = await Product.find({
    organizationId,
    canBePurchased: true,
    status: 'active',
    deletedAt: null,
    'reorderingRules.0': { $exists: true }, // at least one reorder rule
  }).lean()

  scanned = products.length

  for (const product of products as any[]) {
    const productId = String(product._id)
    const productName = String(product.name ?? productId)

    // Sum on-hand across all warehouses
    const onHandQty = await productStockService.getOnHandQty(productId)

    for (const rule of product.reorderingRules ?? []) {
      const minQty = Number(rule.minQty ?? 0)
      const maxQty = Number(rule.maxQty ?? 0)
      const ruleId = String(rule._id ?? '')
      const warehouseId = rule.warehouseId ? String(rule.warehouseId) : null

      // Skip rules that don't apply (stock is sufficient)
      if (onHandQty >= minQty) continue

      // Quantity to order: bring stock up to maxQty, minimum 1
      const qtyToOrder = Math.max(1, maxQty - onHandQty)

      const result: ReorderResult = {
        productId,
        productName,
        ruleId,
        warehouseId,
        onHandQty,
        minQty,
        maxQty,
        qtyToOrder,
        vendorId: '',
        unitPrice: 0,
        poCreated: false,
      }

      try {
        // Use replenish() to find the cheapest vendor from the product's pricelist
        const replenishData = await productStockService.replenish(productId, qtyToOrder, userId)
        result.vendorId = replenishData.vendorId
        result.unitPrice = replenishData.unitPrice

        // Create a draft RFQ (status = rfq)
        const po = await poService.create(
          {
            organizationId,
            vendorId: replenishData.vendorId,
            orderDate: new Date().toISOString(),
            ...(warehouseId ? { deliverToLocationId: warehouseId } : {}),
            items: [
              {
                productId,
                productName,
                quantity: qtyToOrder,
                unitPrice: replenishData.unitPrice,
                lineType: 'product',
              },
            ],
            notes: `Auto-generated by reorder scheduler. Rule: minQty=${minQty} maxQty=${maxQty} onHand=${onHandQty}`,
          },
          userId,
        )

        result.poCreated = true
        result.poId = String((po as any)._id ?? (po as any).id ?? '')
        replenished++

        logger.info(
          `[ReorderScheduler] Created RFQ ${(po as any).seqNo} for ${productName} ` +
          `(qty=${qtyToOrder}, vendor=${replenishData.vendorId}, org=${organizationId})`,
        )
      } catch (err: any) {
        result.error = String(err?.message ?? err ?? 'unknown error')
        logger.error(
          `[ReorderScheduler] Failed to create RFQ for ${productName} (${productId}): ${result.error}`,
        )
      }

      results.push(result)
    }
  }

  return {
    triggered: true,
    scanned,
    replenished,
    products: results,
  }
}
