import type { ErpPermissionAction } from './erp-module-permission'

export type MutationPermissionRule = { moduleKey: string; action: ErpPermissionAction }

function block(
	moduleKey: string,
	entries: Array<[string, ErpPermissionAction]>,
): Record<string, MutationPermissionRule> {
	const out: Record<string, MutationPermissionRule> = {}
	for (const [name, action] of entries) {
		out[name] = { moduleKey, action }
	}
	return out
}

/** Maps GraphQL Mutation field names → ERP sidebar module + required action. Unlisted mutations are not restricted here. */
export const ERP_GRAPHQL_MUTATION_PERMISSIONS: Record<string, MutationPermissionRule> = {
	...block('crm', [
		['createClient', 'create'],
		['updateClient', 'update'],
		['deleteClient', 'delete'],
		['createLead', 'create'],
		['updateLead', 'update'],
		['deleteLead', 'delete'],
		['submitLeadForApproval', 'update'],
		['convertLeadToOpportunity', 'update'],
		['createOpportunity', 'create'],
		['updateOpportunity', 'update'],
		['deleteOpportunity', 'delete'],
	]),
	...block('quotations', [
		['createQuotation', 'create'],
		['updateQuotation', 'update'],
		['deleteQuotation', 'delete'],
		['submitQuotationForApproval', 'update'],
		['sendQuotation', 'update'],
		['createSalesQuotation', 'create'],
		['updateSalesQuotation', 'update'],
		['deleteSalesQuotation', 'delete'],
	]),
	...block('sales', [
		['createSalesEnquiry', 'create'],
		['updateSalesEnquiry', 'update'],
		['deleteSalesEnquiry', 'delete'],
		['submitSalesEnquiryForApproval', 'update'],
		['createSalesOrder', 'create'],
		['updateSalesOrder', 'update'],
		['deleteSalesOrder', 'delete'],
		['submitSalesOrder', 'update'],
		['refundCashSale', 'update'],
		['createDeliveryChallan', 'create'],
		['updateDeliveryChallan', 'update'],
		['deleteDeliveryChallan', 'delete'],
		['submitDeliveryChallanForApproval', 'update'],
		['createSalesReturn', 'create'],
		['updateSalesReturn', 'update'],
		['deleteSalesReturn', 'delete'],
		['submitSalesReturnForApproval', 'update'],
		['createCustomerInvoice', 'create'],
		['updateCustomerInvoice', 'update'],
		['deleteCustomerInvoice', 'delete'],
		['submitCustomerInvoiceForApproval', 'update'],
	]),
	...block('purchases', [
		['createProject', 'create'],
		['updateProject', 'update'],
		['deleteProject', 'delete'],
		['submitProjectForApproval', 'update'],
		['createVendor', 'create'],
		['updateVendor', 'update'],
		['deleteVendor', 'delete'],
		['submitVendorForApproval', 'update'],
		['createPurchaseOrder', 'create'],
		['updatePurchaseOrder', 'update'],
		['deletePurchaseOrder', 'delete'],
		['submitPurchaseOrder', 'update'],
		['approvePurchaseOrder', 'update'],
		['receivePurchaseOrder', 'update'],
		['billPurchaseOrder', 'update'],
		['createMaterialReceipt', 'create'],
		['updateMaterialReceipt', 'update'],
		['deleteMaterialReceipt', 'delete'],
		['submitMaterialReceiptForApproval', 'update'],
		['confirmMaterialReceipt', 'update'],
		['cancelMaterialReceipt', 'update'],
		['createGRN', 'create'],
		['updateGRN', 'update'],
		['deleteGRN', 'delete'],
		['submitGRNForApproval', 'update'],
	]),
	...block('payables', [
		['createVendorBill', 'create'],
		['updateVendorBill', 'update'],
		['deleteVendorBill', 'delete'],
		['approveVendorBill', 'update'],
		['submitVendorBillForApproval', 'update'],
		['createVendorPayment', 'create'],
		['updateVendorPayment', 'update'],
		['deleteVendorPayment', 'delete'],
		['createVendorCredit', 'create'],
		['updateVendorCredit', 'update'],
		['deleteVendorCredit', 'delete'],
		['createVendorPrepayment', 'create'],
		['updateVendorPrepayment', 'update'],
		['deleteVendorPrepayment', 'delete'],
	]),
	...block('inventory', [
		['createWarehouse', 'create'],
		['updateWarehouse', 'update'],
		['createWarehouseBin', 'create'],
		['updateWarehouseBin', 'update'],
		['createInventoryControl', 'create'],
		['updateInventoryControl', 'update'],
		['createStockMovement', 'create'],
		['adjustStock', 'update'],
		['createIntercompanyTransfer', 'create'],
		['updateIntercompanyTransfer', 'update'],
		['confirmIntercompanyTransfer', 'update'],
		['cancelIntercompanyTransfer', 'update'],
		['deleteIntercompanyTransfer', 'delete'],
		['createGoodsReceipt', 'create'],
		['updateGoodsReceipt', 'update'],
		['deleteGoodsReceipt', 'delete'],
		['createStockTransfer', 'create'],
		['updateStockTransfer', 'update'],
		['confirmStockTransfer', 'update'],
		['cancelStockTransfer', 'update'],
		['deleteStockTransfer', 'delete'],
		['createStockAdjustment', 'create'],
		['updateStockAdjustment', 'update'],
		['confirmStockAdjustment', 'update'],
		['cancelStockAdjustment', 'update'],
		['deleteStockAdjustment', 'delete'],
		['createItem', 'create'],
		['updateItem', 'update'],
		['deleteItem', 'delete'],
		['createIPInspection', 'create'],
		['updateIPInspection', 'update'],
		['deleteIPInspection', 'delete'],
		['createInventoryReturn', 'create'],
		['updateInventoryReturn', 'update'],
		['deleteInventoryReturn', 'delete'],
		['createInternalOrder', 'create'],
		['updateInternalOrder', 'update'],
		['deleteInternalOrder', 'delete'],
		['createExciseInvoice', 'create'],
		['updateExciseInvoice', 'update'],
		['deleteExciseInvoice', 'delete'],
		['createAsset', 'create'],
		['updateAsset', 'update'],
		['deleteAsset', 'delete'],
	]),
	...block('products', [
		['createProduct', 'create'],
		['updateProduct', 'update'],
		['deleteProduct', 'delete'],
	]),
	...block('financial', [
		['createJournalEntry', 'create'],
		['updateJournalEntry', 'update'],
		['postJournalEntry', 'update'],
		['deleteJournalEntry', 'delete'],
		['createCurrencyRevaluation', 'create'],
		['postCurrencyRevaluation', 'update'],
		['deleteCurrencyRevaluation', 'delete'],
		['createBudget', 'create'],
		['updateBudget', 'update'],
		['activateBudget', 'update'],
		['deleteBudget', 'delete'],
		['createAllocationSchedule', 'create'],
		['updateAllocationSchedule', 'update'],
		['deleteAllocationSchedule', 'delete'],
		['createGeneralLedger', 'create'],
		['createChartOfAccount', 'create'],
		['updateChartOfAccount', 'update'],
		['deleteChartOfAccount', 'delete'],
	]),
	...block('banks', [
		['createCashBank', 'create'],
		['reconcileCashBank', 'update'],
		['createBankAccount', 'create'],
		['updateBankAccount', 'update'],
		['createBankStatementLine', 'create'],
		['deleteBankStatementLine', 'delete'],
		['matchBankStatementLineToBook', 'update'],
		['createReconciliationRule', 'create'],
		['updateReconciliationRule', 'update'],
		['deleteReconciliationRule', 'delete'],
		['transferBankFunds', 'update'],
	]),
	...block('payroll', [
		['createPayrollManagement', 'create'],
		['updatePayrollManagement', 'update'],
		['deletePayrollManagement', 'delete'],
		['submitPayrollManagementForApproval', 'update'],
		['createPayrollUiRecord', 'create'],
		['updatePayrollUiRecord', 'update'],
		['deletePayrollUiRecord', 'delete'],
		['submitPayrollUiRecordForApproval', 'update'],
		['createSalaryProcessing', 'create'],
		['updateSalaryProcessing', 'update'],
		['deleteSalaryProcessing', 'delete'],
		['createLoanRepayment', 'create'],
		['updateLoanRepayment', 'update'],
		['deleteLoanRepayment', 'delete'],
	]),
	...block('hr', [
		['createLeaveType', 'create'],
		['updateLeaveType', 'update'],
		['deleteLeaveType', 'delete'],
		['createLeaveEnrollment', 'create'],
		['updateLeaveEnrollment', 'update'],
		['deleteLeaveEnrollment', 'delete'],
		['createLeaveApplication', 'create'],
		['updateLeaveApplication', 'update'],
		['deleteLeaveApplication', 'delete'],
		['approveLeaveApplication', 'update'],
		['rejectLeaveApplication', 'update'],
		['createLeaveReinstatement', 'create'],
		['updateLeaveReinstatement', 'update'],
		['approveLeaveReinstatement', 'update'],
		['rejectLeaveReinstatement', 'update'],
		['deleteLeaveReinstatement', 'delete'],
		['createAttendance', 'create'],
		['updateAttendance', 'update'],
		['deleteAttendance', 'delete'],
		['createCareer', 'create'],
		['updateCareer', 'update'],
		['deleteCareer', 'delete'],
		['createRecruitment', 'create'],
		['updateRecruitment', 'update'],
		['createApplicant', 'create'],
		['updateApplicant', 'update'],
		['deleteApplicant', 'delete'],
	]),
	...block('customers', [
		['createCustomer', 'create'],
		['updateCustomer', 'update'],
		['deleteCustomer', 'delete'],
		['createCustomerPayment', 'create'],
		['updateCustomerPayment', 'update'],
		['deleteCustomerPayment', 'delete'],
		['createCustomerRefund', 'create'],
		['cancelCustomerRefund', 'update'],
		['createCustomerDeposit', 'create'],
		['cancelCustomerDeposit', 'update'],
		['generatePriceList', 'create'],
		['upsertIndividualPriceList', 'update'],
		['seedIndividualPriceListFromCatalog', 'update'],
		['deleteIndividualPriceList', 'delete'],
		['draftFinanceChargeAssessment', 'create'],
		['postFinanceChargeAssessment', 'update'],
		['cancelFinanceChargeAssessment', 'update'],
		['deleteFinanceChargeAssessment', 'delete'],
		['createReturnAuthorization', 'create'],
		['approveReturnAuthorization', 'update'],
		['rejectReturnAuthorization', 'update'],
		['cancelReturnAuthorization', 'update'],
		['deleteReturnAuthorization', 'delete'],
		['receiveReturnAuthorizationGoods', 'update'],
	]),
}
